# Variables:
#   acme_url
#
---
name: instant-https

releases:
- name: instant-https
  version: latest
  # sha1: 404a50accba52ee0d6e3d04b9da4ae1484646b2d
  # url: https://github.com/govau/instant-https-boshrelease/releases/download/v4.1.0/instant-https-4.1.0.tgz

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: https_proxy
  instances: 1
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: proxy
    release: instant-https
    properties:
      contact_email: patrick.crocker@gmail.com
      proxies:
      - hostnames:
        - ci.nulldriver.com
        acme_url: ((acme_url))
        backends:
        - "http://10.0.8.4:8080"
        websocket: true
      - hostnames:
        - opsman.nulldriver.com
        acme_url: ((acme_url))
        backends:
        - "https://10.0.10.2:443"
        insecure_skip_verify: true
      - hostnames:
        - api.run.nulldriver.com
        - doppler.run.nulldriver.com
        - p-spring-cloud-services.uaa.run.nulldriver.com
        - spring-cloud-broker.cfapps.nulldriver.com
        - spring-cloud-broker-venerable.cfapps.nulldriver.com
        - pivotal-rabbitmq-broker.run.nulldriver.com
        - redis-broker.run.nulldriver.com
        - cfclitest-broker.cfapps.nulldriver.com
        - login.run.nulldriver.com
        - account.run.nulldriver.com
        - apps.run.nulldriver.com
        - aviato-profile.cfapps.nulldriver.com
        backends:
        - "https://10.0.20.10:443"
        acme_url: ((acme_url))
        websocket: true
        insecure_skip_verify: true
      - hostnames:
        - "*.run.nulldriver.com"
        - "*.cfapps.nulldriver.com"
        backends:
        - "https://10.0.20.10:443"
        acme_url: ((acme_url))
        websocket: true
        insecure_skip_verify: true
  vm_type: micro
  stemcell: default

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
