instance_groups:
- azs: ((azs))
  instances: ((web_instances))
  jobs:
  - name: atc
    properties:
      basic_auth_password: ((atc_basic_auth.password))
      basic_auth_username: ((atc_basic_auth.username))
      external_url: ((external_url))
      log_level: debug
      postgresql:
        database: atc
        role:
          name: concourse
          password: ((postgres_password))
      token_signing_key: ((token_signing_key))
    release: concourse
  - name: tsa
    properties:
      authorized_keys:
      - ((worker_key.public_key))
      host_key: ((tsa_host_key))
      log_level: debug
      token_signing_key: ((token_signing_key))
    release: concourse
  name: web
  networks:
  - name: ((network_name))
  stemcell: trusty
  vm_type: ((web_vm_type))
- azs: ((azs))
  instances: 1
  jobs:
  - name: postgres
    properties:
      databases:
        databases:
        - name: atc
        port: 5432
        roles:
        - name: concourse
          password: ((postgres_password))
    release: postgres
  name: db
  networks:
  - name: ((network_name))
  persistent_disk_type: ((db_persistent_disk_type))
  stemcell: trusty
  vm_type: ((db_vm_type))
- azs: ((azs))
  instances: ((worker_instances))
  jobs:
  - consumes:
      baggageclaim:
        from: worker-baggageclaim
    name: groundcrew
    properties:
      drain_timeout: 10m
      tsa:
        worker_key: ((worker_key))
    release: concourse
  - name: baggageclaim
    properties:
      driver: btrfs
      log_level: debug
    provides:
      baggageclaim:
        as: worker-baggageclaim
    release: concourse
  - name: garden
    properties:
      garden:
        dns_servers: ((internal_dns))
        listen_address: 0.0.0.0:7777
        listen_network: tcp
    release: garden-runc
  name: worker
  networks:
  - name: ((network_name))
  stemcell: trusty
  vm_type: ((worker_vm_type))
name: ((deployment_name))
releases:
- name: concourse
  sha1: 235c704d50e62c9e089865dd43306659d5207690
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.9.1
  version: 3.9.1
- name: garden-runc
  sha1: d9a7901c0502d97c043b857496f0f414a5843e8d
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.11.1
  version: 1.11.1
- name: postgres
  sha1: 20929ee4b0c64fd97072a266311a6d00714124a7
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=25
  version: "25"
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000
variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh
