instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: proxy
    properties:
      contact_email: ((contact_email))
      proxies:
      - acme_url: ((acme_url))
        backends: ((ci_backends))
        hostnames: ((ci_hostnames))
        websocket: true
      - acme_url: ((acme_url))
        backends: ((opsman_backends))
        hostnames: ((opsman_hostnames))
        insecure_skip_verify: true
      - acme_url: ((acme_url))
        backends: ((pas_backends))
        hostnames: ((pas_hostnames))
        insecure_skip_verify: true
        websocket: true
      - acme_url: ((acme_url))
        backends: ((harbor_backends))
        hostnames: ((harbor_hostnames))
    release: instant-https
  name: https_proxy
  networks:
  - name: default
  stemcell: default
  vm_type: micro
name: instant-https
releases:
- name: instant-https
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3468.latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  update_watch_time: 1000-60000
